import type { AcademyDiscipline, AcademyNode } from "./vault";

type NodeBlueprint = {
  id: string;
  title: string;
  summary: string;
  level: number;
  prerequisites: string[];
  track: string;
};

type DisciplineBlueprint = Omit<AcademyDiscipline, "nodes"> & {
  nodes: NodeBlueprint[];
};

const n = (
  id: string,
  title: string,
  summary: string,
  level: number,
  prerequisites: string[],
  track: string,
): NodeBlueprint => ({ id, title, summary, level, prerequisites, track });

const BLUEPRINTS: DisciplineBlueprint[] = [
  {
    id: "mathematics",
    name: "Matematica",
    area: "Ciencias formais",
    summary:
      "Da aritmetica e demonstracao ao calculo, algebra abstrata, geometria e pesquisa matematica.",
    color: "oklch(0.68 0.18 250)",
    nodes: [
      n(
        "number",
        "Numeros e operacoes",
        "Sistemas numericos, estimacao e sentido de grandeza.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "division",
        "Divisao e proporcionalidade",
        "Quocientes, razoes, taxas e escalas.",
        1,
        ["number"],
        "Fundamentos",
      ),
      n(
        "fractions",
        "Fracoes e numeros racionais",
        "Equivalencia, operacoes e representacoes.",
        1,
        ["division"],
        "Fundamentos",
      ),
      n(
        "proof",
        "Logica e demonstracao",
        "Proposicoes, quantificadores, inducao e contradicao.",
        2,
        ["fractions"],
        "Fundamentos",
      ),
      n(
        "algebra",
        "Algebra elementar",
        "Expressoes, equacoes, desigualdades e polinomios.",
        2,
        ["fractions"],
        "Algebra",
      ),
      n(
        "geometry",
        "Geometria euclidiana",
        "Congruencia, semelhanca, construcoes e prova geometrica.",
        2,
        ["proof"],
        "Geometria",
      ),
      n(
        "functions",
        "Funcoes e modelagem",
        "Dominio, imagem, composicao, inversas e familias de funcoes.",
        2,
        ["algebra"],
        "Analise",
      ),
      n(
        "trigonometry",
        "Trigonometria",
        "Circulo, identidades, ondas e coordenadas polares.",
        2,
        ["geometry", "functions"],
        "Geometria",
      ),
      n(
        "analytic-geometry",
        "Geometria analitica",
        "Vetores, retas, conicas e espaco tridimensional.",
        3,
        ["algebra", "geometry"],
        "Geometria",
      ),
      n(
        "calculus-1",
        "Calculo I",
        "Limites, continuidade, derivadas e integracao inicial.",
        3,
        ["functions", "trigonometry"],
        "Analise",
      ),
      n(
        "linear-algebra",
        "Algebra linear",
        "Espacos vetoriais, transformacoes, autovalores e formas canonicas.",
        3,
        ["analytic-geometry", "proof"],
        "Algebra",
      ),
      n(
        "discrete",
        "Matematica discreta",
        "Combinatoria, grafos, recorrencias e estruturas finitas.",
        3,
        ["proof", "algebra"],
        "Discreta",
      ),
      n(
        "calculus-2",
        "Calculo II",
        "Tecnicas de integracao, series e equacoes parametricas.",
        4,
        ["calculus-1"],
        "Analise",
      ),
      n(
        "probability",
        "Probabilidade",
        "Variaveis aleatorias, distribuicoes e convergencia.",
        4,
        ["calculus-1", "discrete"],
        "Probabilidade",
      ),
      n(
        "calculus-3",
        "Calculo III",
        "Derivadas parciais, integrais multiplas e calculo vetorial.",
        4,
        ["calculus-2", "linear-algebra"],
        "Analise",
      ),
      n(
        "differential-equations",
        "Equacoes diferenciais",
        "EDOs, sistemas dinamicos e transformadas.",
        4,
        ["calculus-2", "linear-algebra"],
        "Aplicada",
      ),
      n(
        "real-analysis",
        "Analise real",
        "Construcao rigorosa de limites, medida e integracao.",
        5,
        ["calculus-3", "proof"],
        "Analise",
      ),
      n(
        "abstract-algebra",
        "Algebra abstrata",
        "Grupos, aneis, corpos e simetrias.",
        5,
        ["linear-algebra", "proof"],
        "Algebra",
      ),
      n(
        "topology",
        "Topologia",
        "Espacos topologicos, continuidade, compacidade e conexidade.",
        5,
        ["real-analysis"],
        "Geometria",
      ),
      n(
        "research",
        "Seminario de pesquisa matematica",
        "Leitura de artigos, problemas abertos e escrita de provas.",
        6,
        ["real-analysis", "abstract-algebra"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "statistics",
    name: "Estatistica e Ciencia de Dados",
    area: "Ciencias formais",
    summary: "Inferencia, causalidade, modelagem e computacao para compreender dados reais.",
    color: "oklch(0.7 0.16 205)",
    nodes: [
      n(
        "data-literacy",
        "Leitura critica de dados",
        "Escalas, vieses, visualizacao e incerteza.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "probability",
        "Probabilidade aplicada",
        "Eventos, variaveis e distribuicoes.",
        2,
        ["data-literacy"],
        "Fundamentos",
      ),
      n(
        "descriptive",
        "Estatistica descritiva",
        "Amostras, dispersao, associacao e exploracao.",
        2,
        ["data-literacy"],
        "Inferencia",
      ),
      n(
        "inference",
        "Inferencia estatistica",
        "Estimacao, intervalos e testes de hipotese.",
        3,
        ["probability", "descriptive"],
        "Inferencia",
      ),
      n(
        "regression",
        "Regressao linear",
        "Modelos, diagnostico, interpretacao e regularizacao.",
        3,
        ["inference"],
        "Modelagem",
      ),
      n(
        "bayesian",
        "Estatistica bayesiana",
        "Priors, posteriores, decisao e computacao.",
        4,
        ["probability", "inference"],
        "Inferencia",
      ),
      n(
        "causal",
        "Inferencia causal",
        "Contrafactuais, experimentos e identificacao.",
        4,
        ["regression"],
        "Causalidade",
      ),
      n(
        "machine-learning",
        "Aprendizado de maquina",
        "Classificacao, validacao e generalizacao.",
        4,
        ["regression"],
        "Computacao",
      ),
      n(
        "time-series",
        "Series temporais",
        "Dependencia, previsao e processos estocasticos.",
        5,
        ["regression", "probability"],
        "Modelagem",
      ),
      n(
        "research",
        "Projeto de dados reproduzivel",
        "Pergunta, dados, codigo, argumento e publicacao.",
        6,
        ["causal", "machine-learning"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "physics",
    name: "Fisica",
    area: "Ciencias naturais",
    summary: "Modelos matematicos da materia, movimento, campos, energia, informacao e universo.",
    color: "oklch(0.72 0.15 225)",
    nodes: [
      n(
        "measurement",
        "Medicao e incerteza",
        "Grandezas, unidades, erro e desenho experimental.",
        1,
        [],
        "Laboratorio",
      ),
      n(
        "mechanics",
        "Mecanica classica",
        "Movimento, forcas, energia e momento.",
        2,
        ["measurement"],
        "Mecanica",
      ),
      n(
        "waves",
        "Oscilacoes e ondas",
        "Modos, ressonancia, som e propagacao.",
        2,
        ["mechanics"],
        "Ondas",
      ),
      n(
        "thermodynamics",
        "Termodinamica",
        "Calor, entropia, potenciais e equilibrio.",
        3,
        ["mechanics"],
        "Materia",
      ),
      n(
        "electromagnetism-1",
        "Eletromagnetismo I",
        "Campos, potenciais, circuitos e leis de Maxwell.",
        3,
        ["mechanics"],
        "Campos",
      ),
      n(
        "mathematical-methods",
        "Metodos matematicos",
        "Vetores, EDOs, Fourier e operadores.",
        3,
        ["mechanics"],
        "Metodos",
      ),
      n(
        "optics",
        "Optica",
        "Optica geometrica, interferencia, difracao e polarizacao.",
        3,
        ["waves", "electromagnetism-1"],
        "Ondas",
      ),
      n(
        "analytical-mechanics",
        "Mecanica analitica",
        "Lagrange, Hamilton, simetrias e caos.",
        4,
        ["mathematical-methods", "mechanics"],
        "Mecanica",
      ),
      n(
        "quantum-1",
        "Mecanica quantica I",
        "Estados, operadores, medida e equacao de Schrodinger.",
        4,
        ["waves", "mathematical-methods"],
        "Quantica",
      ),
      n(
        "statistical",
        "Mecanica estatistica",
        "Ensembles, fases e emergencia macroscopica.",
        4,
        ["thermodynamics", "mathematical-methods"],
        "Materia",
      ),
      n(
        "electromagnetism-2",
        "Eletromagnetismo II",
        "Radiacao, relatividade e formulacao covariante.",
        5,
        ["electromagnetism-1", "mathematical-methods"],
        "Campos",
      ),
      n(
        "quantum-2",
        "Mecanica quantica II",
        "Spin, perturbacao, espalhamento e muitos corpos.",
        5,
        ["quantum-1"],
        "Quantica",
      ),
      n(
        "relativity",
        "Relatividade",
        "Espaco-tempo, geometria e gravitacao.",
        5,
        ["analytical-mechanics", "electromagnetism-2"],
        "Gravitacao",
      ),
      n(
        "research",
        "Laboratorio e pesquisa em fisica",
        "Instrumentacao, artigo, reproducao e investigacao autoral.",
        6,
        ["quantum-2", "statistical"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "chemistry",
    name: "Quimica",
    area: "Ciencias naturais",
    summary:
      "Estrutura, transformacao e caracterizacao da materia em escalas atomicas e macromoleculares.",
    color: "oklch(0.72 0.16 165)",
    nodes: [
      n(
        "matter",
        "Materia e estequiometria",
        "Mols, composicao, reacoes e conservacao.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "atomic",
        "Estrutura atomica",
        "Orbitais, periodicidade e ligacao.",
        2,
        ["matter"],
        "Estrutura",
      ),
      n(
        "laboratory",
        "Laboratorio quimico",
        "Seguranca, preparo, medicao e caderno de laboratorio.",
        2,
        ["matter"],
        "Laboratorio",
      ),
      n(
        "thermochemistry",
        "Termoquimica",
        "Energia, entalpia, entropia e espontaneidade.",
        3,
        ["atomic"],
        "Fisico-quimica",
      ),
      n(
        "equilibrium",
        "Equilibrio e cinetica",
        "Acido-base, solubilidade, velocidade e mecanismos.",
        3,
        ["atomic", "laboratory"],
        "Reacoes",
      ),
      n(
        "organic-1",
        "Quimica organica I",
        "Estrutura, estereoquimica e mecanismos fundamentais.",
        3,
        ["atomic"],
        "Organica",
      ),
      n(
        "analytical",
        "Quimica analitica",
        "Separacoes, espectroscopia e validacao de metodos.",
        4,
        ["equilibrium", "laboratory"],
        "Analitica",
      ),
      n(
        "organic-2",
        "Quimica organica II",
        "Sintese, aromaticidade e elucidacao estrutural.",
        4,
        ["organic-1"],
        "Organica",
      ),
      n(
        "inorganic",
        "Quimica inorganica",
        "Coordenacao, simetria, solidos e catalise.",
        4,
        ["atomic", "thermochemistry"],
        "Inorganica",
      ),
      n(
        "physical",
        "Fisico-quimica",
        "Quantica molecular, termodinamica e superficies.",
        5,
        ["thermochemistry", "equilibrium"],
        "Fisico-quimica",
      ),
      n(
        "biochemistry",
        "Bioquimica",
        "Proteinas, metabolismo e energetica celular.",
        5,
        ["organic-2"],
        "Interfaces",
      ),
      n(
        "research",
        "Pesquisa e sintese quimica",
        "Planejamento experimental, caracterizacao e comunicacao.",
        6,
        ["analytical", "physical"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "biology",
    name: "Biologia e Evolucao",
    area: "Ciencias da vida",
    summary: "Vida como sistema celular, historico, ecologico e informacional.",
    color: "oklch(0.7 0.17 145)",
    nodes: [
      n(
        "evolution",
        "Pensamento evolutivo",
        "Selecao, deriva, ancestralidade e adaptacao.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "cell",
        "Biologia celular",
        "Membranas, organelas, energia e divisao.",
        2,
        ["evolution"],
        "Celula",
      ),
      n(
        "genetics",
        "Genetica",
        "Heranca, variacao, expressao e mapas geneticos.",
        2,
        ["cell"],
        "Informacao",
      ),
      n(
        "ecology",
        "Ecologia",
        "Populacoes, comunidades, energia e ciclos.",
        2,
        ["evolution"],
        "Ecologia",
      ),
      n(
        "molecular",
        "Biologia molecular",
        "DNA, RNA, proteinas e regulacao.",
        3,
        ["cell", "genetics"],
        "Informacao",
      ),
      n(
        "physiology",
        "Fisiologia comparada",
        "Homeostase, sistemas e adaptacoes.",
        3,
        ["cell"],
        "Organismos",
      ),
      n(
        "development",
        "Biologia do desenvolvimento",
        "Diferenciacao, forma e evolucao do desenvolvimento.",
        4,
        ["molecular", "genetics"],
        "Organismos",
      ),
      n(
        "microbiology",
        "Microbiologia",
        "Bacterias, arqueias, virus e comunidades microbianas.",
        4,
        ["molecular"],
        "Microbiologia",
      ),
      n(
        "population-genetics",
        "Genetica de populacoes",
        "Frequencias, selecao, coalescencia e especiacao.",
        4,
        ["genetics", "evolution"],
        "Evolucao",
      ),
      n(
        "systems",
        "Biologia de sistemas",
        "Redes, dinamica e integracao multiescala.",
        5,
        ["molecular", "physiology"],
        "Sistemas",
      ),
      n(
        "conservation",
        "Biologia da conservacao",
        "Biodiversidade, risco e restauracao.",
        5,
        ["ecology", "population-genetics"],
        "Ecologia",
      ),
      n(
        "research",
        "Pesquisa biologica",
        "Hipotese, campo, bancada, bioinformatica e artigo.",
        6,
        ["systems", "conservation"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "astronomy",
    name: "Astronomia e Cosmologia",
    area: "Ciencias naturais",
    summary: "Observacao e teoria de planetas, estrelas, galaxias e historia cosmica.",
    color: "oklch(0.68 0.18 285)",
    nodes: [
      n(
        "sky",
        "Ceu e observacao",
        "Coordenadas, tempo, instrumentos e diarios de observacao.",
        1,
        [],
        "Observacao",
      ),
      n(
        "solar-system",
        "Sistema Solar",
        "Origens, dinamica, planetas e pequenos corpos.",
        2,
        ["sky"],
        "Planetaria",
      ),
      n(
        "stellar",
        "Fisica estelar",
        "Espectros, estrutura, evolucao e remanescentes.",
        3,
        ["sky"],
        "Astrofisica",
      ),
      n(
        "galaxies",
        "Galaxias",
        "Morfologia, dinamica, formacao e materia escura.",
        3,
        ["stellar"],
        "Astrofisica",
      ),
      n(
        "observational",
        "Astronomia observacional",
        "Fotometria, espectroscopia e reducao de dados.",
        3,
        ["sky"],
        "Observacao",
      ),
      n(
        "relativity",
        "Relatividade para astronomia",
        "Espaco-tempo, buracos negros e lentes.",
        4,
        ["stellar"],
        "Gravitacao",
      ),
      n(
        "cosmology",
        "Cosmologia",
        "Expansao, fundo cosmico, estrutura e energia escura.",
        4,
        ["galaxies", "relativity"],
        "Cosmologia",
      ),
      n(
        "exoplanets",
        "Exoplanetas e astrobiologia",
        "Deteccao, atmosferas, habitabilidade e vida.",
        4,
        ["solar-system", "observational"],
        "Planetaria",
      ),
      n(
        "high-energy",
        "Astrofisica de altas energias",
        "Acrecao, jatos, ondas gravitacionais e transientes.",
        5,
        ["relativity", "observational"],
        "Astrofisica",
      ),
      n(
        "research",
        "Projeto de pesquisa astronomica",
        "Catalogos, telescopios, simulacao e comunicacao.",
        6,
        ["cosmology", "observational"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "earth-climate",
    name: "Ciencias da Terra e Clima",
    area: "Ciencias naturais",
    summary: "Terra como sistema dinamico: rochas, oceanos, atmosfera, clima e risco.",
    color: "oklch(0.67 0.14 185)",
    nodes: [
      n(
        "earth-system",
        "Sistema Terra",
        "Reservatorios, fluxos, escalas e tempo profundo.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "geology",
        "Geologia",
        "Minerais, rochas, estratigrafia e tectonica.",
        2,
        ["earth-system"],
        "Geosfera",
      ),
      n(
        "meteorology",
        "Meteorologia",
        "Atmosfera, circulacao, nuvens e previsao.",
        2,
        ["earth-system"],
        "Atmosfera",
      ),
      n(
        "oceanography",
        "Oceanografia",
        "Circulacao, quimica, ecossistemas e interfaces.",
        3,
        ["earth-system"],
        "Oceanos",
      ),
      n(
        "geomorphology",
        "Geomorfologia",
        "Relevo, rios, costas e processos superficiais.",
        3,
        ["geology"],
        "Geosfera",
      ),
      n(
        "paleoclimate",
        "Paleoclima",
        "Proxies, ciclos orbitais e historia climatica.",
        4,
        ["geology", "meteorology"],
        "Clima",
      ),
      n(
        "climate-dynamics",
        "Dinamica do clima",
        "Balanco radiativo, feedbacks e variabilidade.",
        4,
        ["meteorology", "oceanography"],
        "Clima",
      ),
      n(
        "hazards",
        "Riscos naturais",
        "Terremotos, vulcoes, extremos e vulnerabilidade.",
        4,
        ["geology", "meteorology"],
        "Risco",
      ),
      n(
        "modeling",
        "Modelagem do sistema Terra",
        "Dados, equacoes, cenarios e incerteza.",
        5,
        ["climate-dynamics"],
        "Metodos",
      ),
      n(
        "research",
        "Pesquisa ambiental integrada",
        "Campo, sensoriamento, modelos e politica ambiental.",
        6,
        ["modeling", "hazards"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "portuguese",
    name: "Lingua Portuguesa e Linguistica",
    area: "Linguagens",
    summary: "Uso rigoroso da lingua, sua historia, estrutura, variacao e poder argumentativo.",
    color: "oklch(0.7 0.17 25)",
    nodes: [
      n(
        "reading",
        "Leitura analitica",
        "Estrutura, inferencia, contexto e leitura lenta.",
        1,
        [],
        "Leitura",
      ),
      n(
        "writing",
        "Escrita clara",
        "Frase, paragrafo, coesao, revisao e estilo.",
        1,
        ["reading"],
        "Escrita",
      ),
      n(
        "grammar",
        "Gramatica descritiva",
        "Morfologia, sintaxe e funcionamento real da lingua.",
        2,
        ["writing"],
        "Estrutura",
      ),
      n(
        "phonetics",
        "Fonetica e fonologia",
        "Sons, prosodia, variacao e sistemas fonologicos.",
        2,
        ["reading"],
        "Linguistica",
      ),
      n(
        "semantics",
        "Semantica e pragmatica",
        "Sentido, referencia, implicatura e contexto.",
        3,
        ["grammar"],
        "Linguistica",
      ),
      n(
        "rhetoric",
        "Retorica e argumentacao",
        "Topicos, figuras, ethos, evidencia e persuasao.",
        3,
        ["writing", "semantics"],
        "Argumentacao",
      ),
      n(
        "history",
        "Historia da lingua portuguesa",
        "Latim, formacao, contatos e mudancas.",
        3,
        ["grammar", "phonetics"],
        "Historia",
      ),
      n(
        "sociolinguistics",
        "Sociolinguistica",
        "Variacao, norma, identidade, poder e preconceito.",
        4,
        ["history", "phonetics"],
        "Sociedade",
      ),
      n(
        "discourse",
        "Analise do discurso",
        "Enunciacao, genero, ideologia e instituicoes.",
        4,
        ["rhetoric", "semantics"],
        "Discurso",
      ),
      n(
        "philology",
        "Filologia e critica textual",
        "Manuscritos, edicoes, transmissao e autoria.",
        5,
        ["history", "reading"],
        "Pesquisa",
      ),
      n(
        "academic-writing",
        "Escrita academica",
        "Problema, revisao, argumento, citacao e publicacao.",
        5,
        ["rhetoric", "discourse"],
        "Escrita",
      ),
      n(
        "research",
        "Pesquisa em linguagem",
        "Corpus, campo, teoria e analise linguistica.",
        6,
        ["academic-writing", "sociolinguistics"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "literature",
    name: "Literatura e Estudos Comparados",
    area: "Humanidades",
    summary: "Obras como formas historicas, esteticas e filosoficas de conhecimento.",
    color: "oklch(0.72 0.16 45)",
    nodes: [
      n(
        "close-reading",
        "Leitura cerrada",
        "Voz, forma, imagem, ritmo e ambiguidade.",
        1,
        [],
        "Metodo",
      ),
      n(
        "genres",
        "Generos literarios",
        "Poesia, drama, conto, romance e ensaio.",
        2,
        ["close-reading"],
        "Forma",
      ),
      n(
        "narratology",
        "Narratologia",
        "Tempo, focalizacao, personagem e mundo ficcional.",
        3,
        ["genres"],
        "Teoria",
      ),
      n(
        "poetics",
        "Poetica",
        "Metro, ritmo, imagem e tradicoes poeticas.",
        3,
        ["genres"],
        "Teoria",
      ),
      n(
        "brazilian",
        "Literatura brasileira",
        "Formacao, movimentos, rupturas e vozes.",
        3,
        ["close-reading"],
        "Tradicoes",
      ),
      n(
        "lusophone",
        "Literaturas lusofonas",
        "Portugal, Africa, Brasil e dialogos pos-coloniais.",
        4,
        ["brazilian"],
        "Tradicoes",
      ),
      n(
        "world",
        "Literatura mundial",
        "Circulacao, traducao, canon e periferias.",
        4,
        ["narratology"],
        "Comparada",
      ),
      n(
        "theory",
        "Teoria literaria",
        "Formalismo, hermeneutica, marxismo e pos-estruturalismo.",
        4,
        ["narratology", "poetics"],
        "Teoria",
      ),
      n(
        "criticism",
        "Critica e ensaio",
        "Interpretar, situar e sustentar uma leitura.",
        5,
        ["theory", "world"],
        "Escrita",
      ),
      n(
        "research",
        "Pesquisa literaria",
        "Arquivo, bibliografia, comparacao e tese.",
        6,
        ["criticism", "lusophone"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "history",
    name: "Historia",
    area: "Humanidades",
    summary: "Investigacao critica das sociedades no tempo por fontes, debates e escalas.",
    color: "oklch(0.68 0.13 75)",
    nodes: [
      n(
        "historical-method",
        "Metodo historico",
        "Fonte, contexto, temporalidade e argumento.",
        1,
        [],
        "Metodo",
      ),
      n(
        "ancient",
        "Mundos antigos",
        "Mesopotamia, Mediterraneo, Africa e Asia antigas.",
        2,
        ["historical-method"],
        "Periodos",
      ),
      n(
        "medieval",
        "Mundos medievais",
        "Cristandades, islam, Asia, Africa e redes.",
        2,
        ["ancient"],
        "Periodos",
      ),
      n(
        "modern",
        "Formacao do mundo moderno",
        "Estados, imperios, comercio e religioes.",
        3,
        ["medieval"],
        "Periodos",
      ),
      n(
        "atlantic",
        "Mundo atlantico e escravidao",
        "Colonizacao, diaspora, resistencia e capitalismo.",
        3,
        ["modern"],
        "Temas",
      ),
      n(
        "brazil",
        "Historia do Brasil",
        "Povos originarios, colonia, imperio, republicas e memoria.",
        3,
        ["modern"],
        "Regioes",
      ),
      n(
        "asia",
        "Historia da Asia",
        "China, Japao, India e redes asiaticas em longa duracao.",
        3,
        ["ancient"],
        "Regioes",
      ),
      n(
        "africa",
        "Historia da Africa",
        "Reinos, islam, colonialismos, independencia e pensamento africano.",
        3,
        ["ancient"],
        "Regioes",
      ),
      n(
        "contemporary",
        "Historia contemporanea",
        "Revolucoes, industria, guerras e ordem global.",
        4,
        ["modern"],
        "Periodos",
      ),
      n(
        "historiography",
        "Historiografia",
        "Escolas, conceitos, disputas e usos do passado.",
        4,
        ["historical-method", "contemporary"],
        "Teoria",
      ),
      n(
        "archives",
        "Arquivos e historia oral",
        "Documento, testemunho, catalogo e etica.",
        5,
        ["historiography"],
        "Metodo",
      ),
      n(
        "global-history",
        "Historia global e conectada",
        "Circulacoes, comparacoes e escalas planetarias.",
        5,
        ["asia", "africa", "atlantic"],
        "Teoria",
      ),
      n(
        "research",
        "Pesquisa historica",
        "Problema, corpus, critica, narrativa e tese.",
        6,
        ["archives", "global-history"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "geography",
    name: "Geografia",
    area: "Humanidades e Terra",
    summary: "Espaco, territorio, ambiente e sociedade por campo, mapas, teoria e geotecnologia.",
    color: "oklch(0.68 0.15 135)",
    nodes: [
      n(
        "spatial-thinking",
        "Pensamento espacial",
        "Escala, lugar, paisagem, rede e territorio.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "cartography",
        "Cartografia",
        "Projecao, simbolizacao, leitura e etica dos mapas.",
        2,
        ["spatial-thinking"],
        "Metodos",
      ),
      n(
        "physical",
        "Geografia fisica",
        "Clima, relevo, solos, aguas e biomas.",
        2,
        ["spatial-thinking"],
        "Ambiente",
      ),
      n(
        "human",
        "Geografia humana",
        "Populacao, cultura, economia e poder.",
        2,
        ["spatial-thinking"],
        "Sociedade",
      ),
      n(
        "urban",
        "Geografia urbana",
        "Cidade, segregacao, mobilidade e planejamento.",
        3,
        ["human"],
        "Sociedade",
      ),
      n(
        "economic",
        "Geografia economica",
        "Trabalho, industria, logistica e globalizacao.",
        3,
        ["human"],
        "Sociedade",
      ),
      n(
        "geopolitics",
        "Geopolitica",
        "Estados, fronteiras, recursos e ordem mundial.",
        3,
        ["human", "cartography"],
        "Politica",
      ),
      n(
        "gis",
        "SIG e sensoriamento remoto",
        "Dados espaciais, imagens, analise e reproducibilidade.",
        4,
        ["cartography"],
        "Geotecnologia",
      ),
      n(
        "environment",
        "Geografia socioambiental",
        "Conflitos, justica ambiental e conservacao.",
        4,
        ["physical", "human"],
        "Ambiente",
      ),
      n(
        "fieldwork",
        "Trabalho de campo",
        "Observacao, entrevista, amostragem e diario espacial.",
        5,
        ["urban", "physical"],
        "Metodos",
      ),
      n(
        "research",
        "Pesquisa geografica",
        "Problema espacial, campo, SIG, teoria e atlas.",
        6,
        ["gis", "fieldwork"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "philosophy",
    name: "Filosofia",
    area: "Humanidades",
    summary: "Leitura rigorosa, argumentacao e investigacao dos problemas fundamentais.",
    color: "oklch(0.7 0.16 315)",
    nodes: [
      n(
        "argument",
        "Argumentacao filosofica",
        "Validade, premissas, objecoes e caridade interpretativa.",
        1,
        [],
        "Metodo",
      ),
      n(
        "ancient",
        "Filosofia antiga",
        "Pre-socraticos, Platao, Aristoteles e escolas helenisticas.",
        2,
        ["argument"],
        "Historia",
      ),
      n(
        "logic",
        "Logica",
        "Proposicional, predicados, modalidade e limites formais.",
        2,
        ["argument"],
        "Metodo",
      ),
      n(
        "medieval",
        "Filosofias medievais",
        "Tradicoes cristas, islamicas e judaicas.",
        3,
        ["ancient"],
        "Historia",
      ),
      n(
        "modern",
        "Filosofia moderna",
        "Racionalismo, empirismo, Kant e idealismo.",
        3,
        ["ancient"],
        "Historia",
      ),
      n(
        "ethics",
        "Etica",
        "Virtude, dever, consequencias, cuidado e vida boa.",
        3,
        ["argument", "ancient"],
        "Pratica",
      ),
      n(
        "epistemology",
        "Epistemologia",
        "Conhecimento, evidencia, ceticismo e injustica epistemica.",
        3,
        ["logic", "modern"],
        "Teorica",
      ),
      n(
        "metaphysics",
        "Metafisica",
        "Ser, identidade, causalidade, tempo e possibilidade.",
        4,
        ["logic", "modern"],
        "Teorica",
      ),
      n(
        "political",
        "Filosofia politica",
        "Justica, liberdade, poder, direito e democracia.",
        4,
        ["ethics", "modern"],
        "Pratica",
      ),
      n(
        "science",
        "Filosofia da ciencia",
        "Explicacao, modelos, confirmacao e mudanca cientifica.",
        4,
        ["epistemology"],
        "Ciencia",
      ),
      n(
        "contemporary",
        "Filosofia contemporanea",
        "Fenomenologia, analitica, critica e pos-colonial.",
        5,
        ["modern", "epistemology"],
        "Historia",
      ),
      n(
        "research",
        "Seminario filosofico",
        "Leitura primaria, reconstrucao, objecao e artigo.",
        6,
        ["contemporary", "metaphysics"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "theology",
    name: "Teologia e Ciencias da Religiao",
    area: "Humanidades",
    summary:
      "Textos, doutrinas, praticas e religioes estudados com profundidade historica e critica.",
    color: "oklch(0.72 0.13 95)",
    nodes: [
      n(
        "method",
        "Metodos do estudo da religiao",
        "Teologia, historia, antropologia e fenomenologia.",
        1,
        [],
        "Metodo",
      ),
      n(
        "hebrew-bible",
        "Biblia Hebraica",
        "Formacao, generos, contextos e exegese.",
        2,
        ["method"],
        "Textos",
      ),
      n(
        "new-testament",
        "Novo Testamento",
        "Contexto greco-romano, textos e cristianismos iniciais.",
        2,
        ["method"],
        "Textos",
      ),
      n(
        "history-christianity",
        "Historia do cristianismo",
        "Patristica, concilios, igrejas e movimentos.",
        3,
        ["hebrew-bible", "new-testament"],
        "Historia",
      ),
      n(
        "systematic",
        "Teologia sistematica",
        "Deus, criacao, cristologia, salvacao e escatologia.",
        3,
        ["new-testament"],
        "Teologia",
      ),
      n(
        "ethics",
        "Etica teologica",
        "Virtudes, consciencia, sociedade, bioetica e politica.",
        3,
        ["systematic"],
        "Pratica",
      ),
      n(
        "judaism-islam",
        "Judaismo e islam",
        "Textos, tradicoes, lei, pensamento e diversidade interna.",
        3,
        ["method"],
        "Comparada",
      ),
      n(
        "asian-religions",
        "Religioes da Asia",
        "Hinduismos, budismos, confucionismos, daoismos e xinto.",
        3,
        ["method"],
        "Comparada",
      ),
      n(
        "hermeneutics",
        "Hermeneutica e exegese",
        "Lingua, genero, historia da recepcao e interpretacao.",
        4,
        ["hebrew-bible", "new-testament"],
        "Metodo",
      ),
      n(
        "philosophy-religion",
        "Filosofia da religiao",
        "Fe, razao, mal, experiencia e pluralismo.",
        4,
        ["systematic", "method"],
        "Teorica",
      ),
      n(
        "sociology-religion",
        "Religiao e sociedade",
        "Secularizacao, ritual, poder, genero e politica.",
        5,
        ["history-christianity", "judaism-islam"],
        "Sociedade",
      ),
      n(
        "research",
        "Pesquisa teologica e religiosa",
        "Fontes, linguas, tradicoes, campo e dissertacao.",
        6,
        ["hermeneutics", "philosophy-religion"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "sociology-anthropology",
    name: "Sociologia e Antropologia",
    area: "Ciencias sociais",
    summary: "Estruturas, culturas, instituicoes e experiencias humanas por teoria e campo.",
    color: "oklch(0.68 0.14 350)",
    nodes: [
      n(
        "social-imagination",
        "Imaginacao sociologica",
        "Biografia, estrutura, historia e problema social.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "classical",
        "Teoria social classica",
        "Marx, Durkheim, Weber e formacao da disciplina.",
        2,
        ["social-imagination"],
        "Teoria",
      ),
      n(
        "anthropology",
        "Teoria antropologica",
        "Cultura, parentesco, troca, simbolo e alteridade.",
        2,
        ["social-imagination"],
        "Teoria",
      ),
      n(
        "methods",
        "Metodos qualitativos",
        "Etnografia, entrevista, observacao e reflexividade.",
        3,
        ["anthropology"],
        "Metodo",
      ),
      n(
        "quantitative",
        "Metodos sociais quantitativos",
        "Amostragem, survey, associacao e desigualdade.",
        3,
        ["classical"],
        "Metodo",
      ),
      n(
        "inequality",
        "Classe, raca e genero",
        "Estratificacao, interseccionalidade e reproducao.",
        3,
        ["classical"],
        "Estruturas",
      ),
      n(
        "institutions",
        "Instituicoes e organizacoes",
        "Estado, familia, escola, religiao e trabalho.",
        4,
        ["classical"],
        "Estruturas",
      ),
      n(
        "culture",
        "Cultura e simbolo",
        "Ritual, midia, gosto, identidade e memoria.",
        4,
        ["anthropology"],
        "Cultura",
      ),
      n(
        "contemporary",
        "Teoria social contemporanea",
        "Poder, campo, redes, colonialidade e agencia.",
        5,
        ["inequality", "culture"],
        "Teoria",
      ),
      n(
        "research",
        "Pesquisa social",
        "Problema, etica, campo, dados e monografia.",
        6,
        ["methods", "quantitative", "contemporary"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "economics",
    name: "Economia",
    area: "Ciencias sociais",
    summary:
      "Escolha, instituicoes, producao, distribuicao e desenvolvimento com teoria e evidencia.",
    color: "oklch(0.72 0.14 115)",
    nodes: [
      n(
        "economic-reasoning",
        "Raciocinio economico",
        "Escassez, incentivos, instituicoes e custo de oportunidade.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "micro-1",
        "Microeconomia I",
        "Preferencias, firma, equilibrio e bem-estar.",
        2,
        ["economic-reasoning"],
        "Microeconomia",
      ),
      n(
        "macro-1",
        "Macroeconomia I",
        "Contas nacionais, crescimento, inflacao e desemprego.",
        2,
        ["economic-reasoning"],
        "Macroeconomia",
      ),
      n(
        "history",
        "Historia economica",
        "Capitalismo, industria, trabalho e crises.",
        2,
        ["economic-reasoning"],
        "Historia",
      ),
      n(
        "econometrics",
        "Econometria",
        "Regressao, identificacao, painel e series temporais.",
        3,
        ["micro-1", "macro-1"],
        "Metodos",
      ),
      n(
        "micro-2",
        "Microeconomia II",
        "Jogos, informacao, desenho de mecanismos e organizacao industrial.",
        4,
        ["micro-1"],
        "Microeconomia",
      ),
      n(
        "macro-2",
        "Macroeconomia II",
        "Modelos dinamicos, moeda, ciclos e politica.",
        4,
        ["macro-1"],
        "Macroeconomia",
      ),
      n(
        "development",
        "Economia do desenvolvimento",
        "Pobreza, saude, educacao, instituicoes e experimentos.",
        4,
        ["econometrics", "history"],
        "Aplicada",
      ),
      n(
        "public",
        "Economia publica e politica",
        "Tributacao, bens publicos, desigualdade e escolha coletiva.",
        4,
        ["micro-2", "econometrics"],
        "Aplicada",
      ),
      n(
        "international",
        "Economia internacional",
        "Comercio, financas, cambio e cadeias globais.",
        5,
        ["macro-2", "micro-2"],
        "Aplicada",
      ),
      n(
        "research",
        "Pesquisa economica",
        "Modelo, identificacao, dados e artigo.",
        6,
        ["econometrics", "development"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "law-politics",
    name: "Direito e Ciencia Politica",
    area: "Ciencias sociais",
    summary:
      "Instituicoes, normas, poder e conflitos estudados por doutrina, historia e evidencia.",
    color: "oklch(0.66 0.15 35)",
    nodes: [
      n(
        "institutions",
        "Estado, norma e instituicao",
        "Autoridade, legitimidade, jurisdicao e cidadania.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "constitutional",
        "Direito constitucional",
        "Constituicao, poderes, direitos e controle.",
        2,
        ["institutions"],
        "Direito",
      ),
      n(
        "political-theory",
        "Teoria politica",
        "Estado, liberdade, igualdade, democracia e representacao.",
        2,
        ["institutions"],
        "Politica",
      ),
      n(
        "civil",
        "Direito civil",
        "Pessoas, obrigacoes, contratos, familia e propriedade.",
        3,
        ["institutions"],
        "Direito",
      ),
      n(
        "criminal",
        "Direito penal e criminologia",
        "Crime, pena, processo, seletividade e seguranca.",
        3,
        ["constitutional"],
        "Direito",
      ),
      n(
        "comparative-politics",
        "Politica comparada",
        "Regimes, partidos, eleicoes e instituicoes.",
        3,
        ["political-theory"],
        "Politica",
      ),
      n(
        "international",
        "Direito e relacoes internacionais",
        "Soberania, tratados, guerra, cooperacao e direitos humanos.",
        4,
        ["constitutional", "political-theory"],
        "Global",
      ),
      n(
        "administrative",
        "Direito administrativo e politicas publicas",
        "Burocracia, regulacao, servicos e avaliacao.",
        4,
        ["constitutional"],
        "Estado",
      ),
      n(
        "legal-reasoning",
        "Interpretacao e argumentacao juridica",
        "Precedente, principios, prova e decisao.",
        4,
        ["civil", "constitutional"],
        "Metodo",
      ),
      n(
        "empirical",
        "Metodos empiricos em politica e direito",
        "Dados, desenho de pesquisa e avaliacao institucional.",
        5,
        ["comparative-politics", "administrative"],
        "Metodo",
      ),
      n(
        "research",
        "Pesquisa juridica e politica",
        "Problema, fontes, casos, dados e tese.",
        6,
        ["legal-reasoning", "empirical"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "psychology",
    name: "Psicologia e Ciencias Cognitivas",
    area: "Ciencias humanas",
    summary: "Mente e comportamento por experimentacao, clinica, neurociencia e contexto social.",
    color: "oklch(0.7 0.17 330)",
    nodes: [
      n(
        "scientific-psychology",
        "Psicologia cientifica",
        "Teorias, evidencia, medicao e replicacao.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "development",
        "Desenvolvimento humano",
        "Cognicao, afeto, apego e ciclo de vida.",
        2,
        ["scientific-psychology"],
        "Desenvolvimento",
      ),
      n(
        "cognition",
        "Cognicao",
        "Percepcao, atencao, memoria, linguagem e decisao.",
        2,
        ["scientific-psychology"],
        "Cognicao",
      ),
      n(
        "social",
        "Psicologia social",
        "Identidade, influencia, grupos e cultura.",
        2,
        ["scientific-psychology"],
        "Sociedade",
      ),
      n(
        "neuroscience",
        "Neurociencia",
        "Neuronios, sistemas, plasticidade e metodos.",
        3,
        ["cognition"],
        "Biologica",
      ),
      n(
        "methods",
        "Metodos e psicometria",
        "Experimentos, testes, validade, estatistica e etica.",
        3,
        ["scientific-psychology"],
        "Metodo",
      ),
      n(
        "personality",
        "Personalidade e diferencas individuais",
        "Modelos, temperamento, inteligencia e contexto.",
        3,
        ["development", "methods"],
        "Individuo",
      ),
      n(
        "psychopathology",
        "Psicopatologia",
        "Modelos, classificacao, sofrimento e cultura.",
        4,
        ["development", "neuroscience"],
        "Clinica",
      ),
      n(
        "clinical",
        "Teorias e praticas clinicas",
        "Avaliacao, formulacao, intervencoes e limites profissionais.",
        5,
        ["psychopathology", "methods"],
        "Clinica",
      ),
      n(
        "computational",
        "Ciencia cognitiva computacional",
        "Modelos, aprendizagem, decisao e simulacao.",
        5,
        ["cognition", "methods"],
        "Cognicao",
      ),
      n(
        "research",
        "Pesquisa em mente e comportamento",
        "Protocolo, etica, dados e comunicacao.",
        6,
        ["neuroscience", "methods"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "computer-science",
    name: "Ciencia da Computacao",
    area: "Ciencias formais e tecnologia",
    summary: "Computacao como ciencia de representacao, algoritmo, linguagem e sistema.",
    color: "oklch(0.67 0.19 270)",
    nodes: [
      n(
        "computational-thinking",
        "Pensamento computacional",
        "Decomposicao, abstracao, algoritmo e depuracao.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "programming",
        "Programacao",
        "Tipos, controle, funcoes, testes e modularidade.",
        2,
        ["computational-thinking"],
        "Software",
      ),
      n(
        "discrete",
        "Estruturas discretas",
        "Logica, conjuntos, grafos, combinatoria e prova.",
        2,
        ["computational-thinking"],
        "Teoria",
      ),
      n(
        "data-structures",
        "Estruturas de dados",
        "Listas, arvores, tabelas, grafos e invariantes.",
        3,
        ["programming", "discrete"],
        "Algoritmos",
      ),
      n(
        "algorithms",
        "Algoritmos",
        "Correcao, complexidade, paradigmas e limites.",
        3,
        ["data-structures"],
        "Algoritmos",
      ),
      n(
        "architecture",
        "Arquitetura de computadores",
        "Logica digital, processador, memoria e desempenho.",
        3,
        ["programming"],
        "Sistemas",
      ),
      n(
        "languages",
        "Linguagens de programacao",
        "Semantica, tipos, paradigmas e interpretadores.",
        4,
        ["programming", "discrete"],
        "Software",
      ),
      n(
        "operating-systems",
        "Sistemas operacionais",
        "Processos, concorrencia, memoria e arquivos.",
        4,
        ["architecture", "data-structures"],
        "Sistemas",
      ),
      n(
        "databases",
        "Bancos de dados",
        "Modelagem, consultas, transacoes e sistemas distribuidos.",
        4,
        ["data-structures"],
        "Dados",
      ),
      n(
        "networks",
        "Redes de computadores",
        "Protocolos, roteamento, transporte e Internet.",
        4,
        ["architecture"],
        "Sistemas",
      ),
      n(
        "security",
        "Seguranca da computacao",
        "Ameacas, criptografia, sistemas e engenharia de seguranca.",
        5,
        ["networks", "operating-systems"],
        "Seguranca",
      ),
      n(
        "ai",
        "Inteligencia artificial",
        "Busca, representacao, aprendizagem e avaliacao.",
        5,
        ["algorithms", "discrete"],
        "IA",
      ),
      n(
        "distributed",
        "Sistemas distribuidos",
        "Consenso, falhas, replicacao e observabilidade.",
        5,
        ["networks", "databases"],
        "Sistemas",
      ),
      n(
        "theory",
        "Teoria da computacao",
        "Automatos, computabilidade e complexidade.",
        5,
        ["algorithms", "discrete"],
        "Teoria",
      ),
      n(
        "research",
        "Pesquisa e engenharia de software",
        "Literatura, experimento, artefato e reproducibilidade.",
        6,
        ["theory", "distributed"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "electrical-engineering",
    name: "Engenharia Eletrica e Eletronica",
    area: "Engenharias",
    summary: "Circuitos, sinais, energia, controle, comunicacao e sistemas embarcados.",
    color: "oklch(0.78 0.16 95)",
    nodes: [
      n(
        "safety",
        "Seguranca e medicao eletrica",
        "Risco, aterramento, multimetro e bancada.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "circuits-1",
        "Circuitos I",
        "Leis, equivalentes, transitorios e potencia.",
        2,
        ["safety"],
        "Circuitos",
      ),
      n(
        "digital",
        "Sistemas digitais",
        "Logica, circuitos combinacionais, sequenciais e HDL.",
        2,
        ["safety"],
        "Digital",
      ),
      n(
        "electronics-1",
        "Eletronica analogica",
        "Diodos, transistores, amplificadores e fontes.",
        3,
        ["circuits-1"],
        "Eletronica",
      ),
      n(
        "signals",
        "Sinais e sistemas",
        "Convolucao, Fourier, Laplace e amostragem.",
        3,
        ["circuits-1"],
        "Sinais",
      ),
      n(
        "electromagnetics",
        "Eletromagnetismo aplicado",
        "Campos, linhas, ondas e antenas.",
        3,
        ["circuits-1"],
        "Campos",
      ),
      n(
        "control",
        "Sistemas de controle",
        "Modelagem, estabilidade, realimentacao e projeto.",
        4,
        ["signals"],
        "Controle",
      ),
      n(
        "embedded",
        "Sistemas embarcados",
        "Microcontroladores, interfaces, tempo real e firmware.",
        4,
        ["digital", "electronics-1"],
        "Computacao",
      ),
      n(
        "power",
        "Sistemas de potencia",
        "Maquinas, conversao, redes, protecao e qualidade.",
        4,
        ["circuits-1", "electromagnetics"],
        "Energia",
      ),
      n(
        "communications",
        "Comunicacoes",
        "Modulacao, ruido, codificacao e enlaces.",
        5,
        ["signals", "electromagnetics"],
        "Comunicacao",
      ),
      n(
        "power-electronics",
        "Eletronica de potencia",
        "Conversores, acionamentos e energia renovavel.",
        5,
        ["electronics-1", "power"],
        "Energia",
      ),
      n(
        "research",
        "Projeto eletrico integrado",
        "Requisitos, simulacao, prototipo, teste e documentacao.",
        6,
        ["control", "embedded"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "mechanical-engineering",
    name: "Engenharia Mecanica",
    area: "Engenharias",
    summary: "Forcas, materiais, maquinas, fluidos, calor, manufatura e projeto.",
    color: "oklch(0.68 0.12 125)",
    nodes: [
      n(
        "workshop",
        "Oficina, desenho e seguranca",
        "Ferramentas, tolerancias, desenho tecnico e pratica segura.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "statics",
        "Estatica",
        "Equilibrio, estruturas, atrito e centros de massa.",
        2,
        ["workshop"],
        "Mecanica",
      ),
      n(
        "dynamics",
        "Dinamica",
        "Cinematica, cinetica, energia e vibracoes.",
        3,
        ["statics"],
        "Mecanica",
      ),
      n(
        "materials",
        "Materiais de engenharia",
        "Estrutura, propriedades, falha e selecao.",
        3,
        ["statics"],
        "Materiais",
      ),
      n(
        "thermodynamics",
        "Termodinamica aplicada",
        "Ciclos, motores, refrigeracao e eficiencia.",
        3,
        ["statics"],
        "Energia",
      ),
      n(
        "fluids",
        "Mecanica dos fluidos",
        "Conservacao, escoamentos, bombas e aerodinamica.",
        4,
        ["dynamics"],
        "Fluidos",
      ),
      n(
        "solid-mechanics",
        "Mecanica dos solidos",
        "Tensao, deformacao, flambagem e fadiga.",
        4,
        ["materials", "statics"],
        "Estruturas",
      ),
      n(
        "manufacturing",
        "Processos de fabricacao",
        "Usinagem, conformacao, solda, aditiva e metrologia.",
        4,
        ["materials", "workshop"],
        "Manufatura",
      ),
      n(
        "machines",
        "Elementos de maquinas",
        "Eixos, engrenagens, mancais, molas e transmissoes.",
        5,
        ["solid-mechanics", "dynamics"],
        "Projeto",
      ),
      n(
        "control",
        "Mecatronica e controle",
        "Sensores, atuadores, modelos e automacao.",
        5,
        ["dynamics"],
        "Sistemas",
      ),
      n(
        "vehicles",
        "Sistemas veiculares",
        "Motores, transmissao, chassis, freios e diagnostico.",
        5,
        ["machines", "thermodynamics"],
        "Mobilidade",
      ),
      n(
        "research",
        "Projeto mecanico",
        "Requisitos, CAD, simulacao, prototipo e validacao.",
        6,
        ["machines", "manufacturing"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "civil-architecture",
    name: "Engenharia Civil e Arquitetura",
    area: "Engenharias",
    summary: "Edificios, cidades e infraestruturas como sistemas tecnicos, humanos e ambientais.",
    color: "oklch(0.69 0.12 65)",
    nodes: [
      n(
        "representation",
        "Desenho, espaco e representacao",
        "Escala, geometria, desenho tecnico e leitura de projeto.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "materials",
        "Materiais de construcao",
        "Concreto, aco, madeira, alvenaria e durabilidade.",
        2,
        ["representation"],
        "Construcao",
      ),
      n(
        "surveying",
        "Topografia e geodesia",
        "Levantamento, coordenadas, nivelamento e implantacao.",
        2,
        ["representation"],
        "Territorio",
      ),
      n(
        "structural-analysis",
        "Analise estrutural",
        "Cargas, esforcos, deformacoes e estabilidade.",
        3,
        ["materials"],
        "Estruturas",
      ),
      n(
        "soil",
        "Mecanica dos solos e fundacoes",
        "Tensoes, resistencia, recalque e contencoes.",
        3,
        ["surveying"],
        "Geotecnia",
      ),
      n(
        "hydraulics",
        "Hidraulica e saneamento",
        "Escoamento, redes, drenagem, agua e esgoto.",
        3,
        ["surveying"],
        "Infraestrutura",
      ),
      n(
        "building-systems",
        "Sistemas prediais",
        "Eletrica, hidraulica, incendio, conforto e eficiencia.",
        4,
        ["materials"],
        "Edificacoes",
      ),
      n(
        "structures",
        "Projeto de estruturas",
        "Concreto, aco, madeira e desempenho.",
        4,
        ["structural-analysis", "soil"],
        "Estruturas",
      ),
      n(
        "architecture",
        "Historia e teoria da arquitetura",
        "Forma, programa, tecnica, cultura e cidade.",
        4,
        ["representation"],
        "Arquitetura",
      ),
      n(
        "urbanism",
        "Urbanismo e mobilidade",
        "Uso do solo, transporte, espaco publico e desigualdade.",
        5,
        ["architecture", "surveying"],
        "Cidade",
      ),
      n(
        "management",
        "Planejamento e gestao de obras",
        "Orcamento, cronograma, qualidade, risco e BIM.",
        5,
        ["building-systems", "structures"],
        "Gestao",
      ),
      n(
        "research",
        "Projeto integrado do ambiente construido",
        "Lugar, programa, estrutura, sistemas e impacto.",
        6,
        ["urbanism", "management"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "medicine",
    name: "Medicina e Ciencias da Saude",
    area: "Ciencias da vida",
    summary: "Corpo, doenca, cuidado e saude coletiva com base cientifica e etica.",
    color: "oklch(0.72 0.15 15)",
    nodes: [
      n(
        "health-literacy",
        "Alfabetizacao em saude",
        "Evidencia, risco, prevencao e limites do autocuidado.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "anatomy",
        "Anatomia humana",
        "Organizacao corporal, sistemas e relacoes espaciais.",
        2,
        ["health-literacy"],
        "Bases",
      ),
      n(
        "physiology",
        "Fisiologia humana",
        "Homeostase, integracao e funcao dos sistemas.",
        2,
        ["anatomy"],
        "Bases",
      ),
      n(
        "biochemistry",
        "Bioquimica e metabolismo",
        "Energia, macromoleculas, sinalizacao e nutricao.",
        2,
        ["health-literacy"],
        "Bases",
      ),
      n(
        "pathology",
        "Patologia geral",
        "Lesao, inflamacao, neoplasia e mecanismos de doenca.",
        3,
        ["physiology", "biochemistry"],
        "Doenca",
      ),
      n(
        "microbiology",
        "Microbiologia e imunologia",
        "Patogenos, defesa, vacinas e resistencia.",
        3,
        ["biochemistry"],
        "Doenca",
      ),
      n(
        "pharmacology",
        "Farmacologia",
        "Alvos, dose, efeitos, interacoes e seguranca.",
        4,
        ["physiology", "pathology"],
        "Terapia",
      ),
      n(
        "clinical-reasoning",
        "Raciocinio clinico",
        "Historia, exame, hipoteses, testes e decisao.",
        4,
        ["pathology", "anatomy"],
        "Clinica",
      ),
      n(
        "epidemiology",
        "Epidemiologia e saude coletiva",
        "Frequencia, causalidade, rastreio e sistemas de saude.",
        4,
        ["health-literacy"],
        "Populacao",
      ),
      n(
        "ethics",
        "Bioetica e relacao de cuidado",
        "Autonomia, justica, comunicacao e fim de vida.",
        4,
        ["clinical-reasoning"],
        "Etica",
      ),
      n(
        "evidence",
        "Medicina baseada em evidencias",
        "Pergunta, estudo, vies, efeito e aplicabilidade.",
        5,
        ["epidemiology", "clinical-reasoning"],
        "Metodo",
      ),
      n(
        "research",
        "Pesquisa em saude",
        "Protocolo, etica, dados, ensaio e translacao.",
        6,
        ["evidence", "ethics"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "agriculture-ecology",
    name: "Agricultura, Alimentos e Ecologia",
    area: "Ciencias aplicadas",
    summary: "Solo, plantas, animais, alimentos e paisagens como sistemas vivos e produtivos.",
    color: "oklch(0.7 0.16 125)",
    nodes: [
      n(
        "agroecosystems",
        "Agroecossistemas",
        "Energia, nutrientes, diversidade e producao.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "soil",
        "Ciencia do solo",
        "Formacao, fisica, quimica, biologia e conservacao.",
        2,
        ["agroecosystems"],
        "Solo",
      ),
      n(
        "plant",
        "Fisiologia e producao vegetal",
        "Crescimento, nutricao, melhoramento e manejo.",
        2,
        ["agroecosystems"],
        "Plantas",
      ),
      n(
        "animal",
        "Ciencia animal",
        "Fisiologia, nutricao, bem-estar e sistemas de criacao.",
        2,
        ["agroecosystems"],
        "Animais",
      ),
      n(
        "ecology",
        "Ecologia aplicada",
        "Populacoes, paisagens, servicos e restauracao.",
        3,
        ["agroecosystems"],
        "Ecologia",
      ),
      n(
        "food",
        "Ciencia dos alimentos",
        "Composicao, processamento, microbiologia e seguranca.",
        3,
        ["plant", "animal"],
        "Alimentos",
      ),
      n(
        "water",
        "Agua e irrigacao",
        "Balanco, drenagem, eficiencia e qualidade.",
        4,
        ["soil", "plant"],
        "Recursos",
      ),
      n(
        "agroecology",
        "Agroecologia",
        "Diversificacao, saberes, resiliencia e justica alimentar.",
        4,
        ["ecology", "soil"],
        "Sistemas",
      ),
      n(
        "economics",
        "Economia e politica rural",
        "Cadeias, terra, trabalho, mercados e governanca.",
        5,
        ["food", "agroecology"],
        "Sociedade",
      ),
      n(
        "research",
        "Projeto de sistema alimentar",
        "Campo, experimento, ciclo de vida e intervencao.",
        6,
        ["economics", "water"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "arts-music",
    name: "Artes Visuais e Musica",
    area: "Artes",
    summary: "Percepcao, tecnica, historia, composicao e critica como formas de investigacao.",
    color: "oklch(0.72 0.19 340)",
    nodes: [
      n(
        "perception",
        "Percepcao e linguagem visual",
        "Forma, cor, espaco, ritmo e composicao.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "drawing",
        "Desenho",
        "Observacao, gesto, perspectiva e construcao.",
        2,
        ["perception"],
        "Visual",
      ),
      n(
        "music-literacy",
        "Escuta e alfabetizacao musical",
        "Pulso, altura, timbre, forma e notacao.",
        2,
        ["perception"],
        "Musica",
      ),
      n(
        "art-history",
        "Historia da arte",
        "Objetos, imagens, instituicoes e contextos globais.",
        3,
        ["perception"],
        "Historia",
      ),
      n(
        "harmony",
        "Harmonia e contraponto",
        "Vozes, funcoes, tensao e conducao.",
        3,
        ["music-literacy"],
        "Musica",
      ),
      n(
        "studio",
        "Atelie e materiais",
        "Pintura, gravura, escultura, fotografia e processo.",
        3,
        ["drawing"],
        "Visual",
      ),
      n(
        "composition",
        "Composicao musical",
        "Motivo, forma, arranjo, orquestracao e tecnologia.",
        4,
        ["harmony"],
        "Musica",
      ),
      n(
        "aesthetics",
        "Estetica e critica",
        "Experiencia, valor, interpretacao e politica da arte.",
        4,
        ["art-history"],
        "Teoria",
      ),
      n(
        "media",
        "Cinema, som e novas midias",
        "Montagem, narrativa audiovisual, instalacao e interatividade.",
        4,
        ["studio", "music-literacy"],
        "Midia",
      ),
      n(
        "practice",
        "Pratica autoral",
        "Pesquisa de linguagem, iteracao, portfolio e apresentacao.",
        5,
        ["composition", "studio"],
        "Criacao",
      ),
      n(
        "research",
        "Pesquisa em artes",
        "Arquivo, pratica, critica, curadoria e memoria do processo.",
        6,
        ["practice", "aesthetics"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "education",
    name: "Educacao e Ciencias da Aprendizagem",
    area: "Ciencias humanas",
    summary: "Como pessoas aprendem, ensinam, avaliam e constroem ambientes intelectuais.",
    color: "oklch(0.73 0.15 80)",
    nodes: [
      n(
        "learning",
        "Teorias da aprendizagem",
        "Memoria, cognicao, experiencia, cultura e motivacao.",
        1,
        [],
        "Fundamentos",
      ),
      n(
        "history",
        "Historia e filosofia da educacao",
        "Ideias, instituicoes, infancia e sociedade.",
        2,
        ["learning"],
        "Fundamentos",
      ),
      n(
        "development",
        "Desenvolvimento e diferencas",
        "Trajetorias, neurodiversidade, linguagem e contexto.",
        2,
        ["learning"],
        "Pessoa",
      ),
      n(
        "curriculum",
        "Curriculo como arquitetura",
        "Selecao, sequencia, profundidade e interdisciplinaridade.",
        3,
        ["history", "learning"],
        "Design",
      ),
      n(
        "instruction",
        "Design de experiencias de aprendizagem",
        "Problemas, exemplos, pratica, feedback e transferencia.",
        3,
        ["learning"],
        "Design",
      ),
      n(
        "assessment",
        "Avaliacao para aprender",
        "Evidencia, criterios, diagnostico e metacognicao.",
        4,
        ["instruction"],
        "Avaliacao",
      ),
      n(
        "technology",
        "Tecnologia e ambientes de aprendizagem",
        "Midia, simulacao, autoria, dados e acessibilidade.",
        4,
        ["instruction"],
        "Ambientes",
      ),
      n(
        "teaching",
        "Didatica disciplinar",
        "Como cada campo pensa, prova, interpreta e cria.",
        5,
        ["curriculum", "assessment"],
        "Lecionamento",
      ),
      n(
        "mentoring",
        "Mentoria e formacao humana",
        "Autonomia, cuidado, dialogo e comunidade intelectual.",
        5,
        ["development", "teaching"],
        "Relacao",
      ),
      n(
        "research",
        "Pesquisa em educacao",
        "Observacao, desenho, intervencao e estudo de aprendizagem.",
        6,
        ["assessment", "mentoring"],
        "Pesquisa",
      ),
    ],
  },
  {
    id: "classics-languages",
    name: "Linguas Classicas e Estudos Asiaticos",
    area: "Linguagens e culturas",
    summary: "Linguas, textos e tradicoes estudados em seus contextos historicos e comparados.",
    color: "oklch(0.69 0.13 55)",
    nodes: [
      n(
        "language-method",
        "Como aprender linguas academicamente",
        "Fonetica, gramatica, vocabulario, corpus e traducao.",
        1,
        [],
        "Metodo",
      ),
      n(
        "latin",
        "Latim",
        "Morfologia, sintaxe, leitura e tradicao textual.",
        2,
        ["language-method"],
        "Classicas",
      ),
      n(
        "greek",
        "Grego antigo",
        "Escrita, morfologia, sintaxe e leitura.",
        2,
        ["language-method"],
        "Classicas",
      ),
      n(
        "japanese",
        "Lingua japonesa",
        "Escritas, gramatica, leitura, escuta e pragmatica.",
        2,
        ["language-method"],
        "Asia",
      ),
      n(
        "chinese",
        "Lingua chinesa",
        "Tons, caracteres, gramatica, leitura e cultura textual.",
        2,
        ["language-method"],
        "Asia",
      ),
      n(
        "classical-texts",
        "Textos classicos mediterraneos",
        "Historia, filosofia, poesia e recepcao.",
        3,
        ["latin", "greek"],
        "Classicas",
      ),
      n(
        "east-asian-thought",
        "Pensamento do Leste Asiatico",
        "Confucionismos, budismos, daoismos e modernidades.",
        3,
        ["japanese", "chinese"],
        "Asia",
      ),
      n(
        "translation",
        "Teoria e pratica da traducao",
        "Equivalencia, estilo, contexto, etica e comentario.",
        4,
        ["classical-texts", "east-asian-thought"],
        "Traducao",
      ),
      n(
        "philology",
        "Filologia comparada",
        "Manuscritos, mudanca linguistica e transmissao.",
        5,
        ["translation"],
        "Pesquisa",
      ),
      n(
        "research",
        "Seminario de textos e culturas",
        "Leitura original, comentario, comparacao e artigo.",
        6,
        ["philology"],
        "Pesquisa",
      ),
    ],
  },
];

function buildDiscipline(blueprint: DisciplineBlueprint): AcademyDiscipline {
  const rowsByLevel = new Map<number, number>();
  const nodes: AcademyNode[] = blueprint.nodes.map((node) => {
    const row = rowsByLevel.get(node.level) ?? 0;
    rowsByLevel.set(node.level, row + 1);
    return {
      id: `${blueprint.id}.${node.id}`,
      disciplineId: blueprint.id,
      subject: node.track,
      title: node.title,
      summary: node.summary,
      level: node.level,
      prerequisites: node.prerequisites.map((id) => `${blueprint.id}.${id}`),
      rewardType: node.level >= 5 ? "arquivo" : node.level >= 3 ? "aula" : "lembrete",
      rewardLabel:
        node.level >= 5
          ? `Dossie de aprofundamento: ${node.title}`
          : node.level >= 3
            ? `Estudo guiado: ${node.title}`
            : `Mapa de conceitos: ${node.title}`,
      x: 40 + (node.level - 1) * 250,
      y: 30 + row * 118,
      color: blueprint.color,
    };
  });
  return { ...blueprint, nodes };
}

export const ACADEMY_DISCIPLINES = BLUEPRINTS.map(buildDiscipline);
export const ACADEMY_NODES = ACADEMY_DISCIPLINES.flatMap((discipline) => discipline.nodes);
