import type { Pillar } from "./types";

export const INITIAL_PILLAR_INDEX = 2;

export const PILLARS: Pillar[] = [
  {
    id: "knowledge",
    index: "01",
    name: "Knowledge",
    purpose: "Structured learning and intellectual growth.",
    tagline: "What you've studied, read, understood.",
    toneLabel: "COOL BLUE-VIOLET · ANALYTICAL",
    hue: "oklch(0.7 0.16 265)",
    hue2: "oklch(0.6 0.18 240)",
    domains: [
      {
        id: "books",
        name: "Books",
        blurb: "Volumes read, in flight, shelved.",
        count: 248,
        icon: "book-open",
      },
      {
        id: "courses",
        name: "Courses",
        blurb: "Long-form study.",
        count: 17,
        icon: "graduation-cap",
      },
      {
        id: "articles",
        name: "Articles",
        blurb: "Essays, papers, posts.",
        count: 612,
        icon: "file-text",
      },
      {
        id: "pdfs",
        name: "PDFs",
        blurb: "Documents and references.",
        count: 84,
        icon: "file-type",
      },
      {
        id: "concepts",
        name: "Concepts",
        blurb: "Ideas you've internalised.",
        count: 1402,
        icon: "brain",
      },
      {
        id: "math",
        name: "Mathematics",
        blurb: "Proofs, problems, methods.",
        count: 96,
        icon: "sigma",
      },
      {
        id: "physics",
        name: "Physics",
        blurb: "Laws, intuitions, models.",
        count: 73,
        icon: "atom",
      },
      {
        id: "programming",
        name: "Programming",
        blurb: "Languages, paradigms, craft.",
        count: 134,
        icon: "cpu",
      },
      {
        id: "psychology",
        name: "Psychology",
        blurb: "Mind, behaviour, self.",
        count: 58,
        icon: "brain",
      },
    ],
    recent: [
      { kind: "BOOK", title: "The Order of Time", meta: "Rovelli · ch. 6 of 13" },
      { kind: "CONCEPT", title: "Emergence", meta: "linked to 38 entities" },
      { kind: "PAPER", title: "Attention Is All You Need", meta: "annotated · 2025" },
      { kind: "COURSE", title: "Linear Algebra — MIT 18.06", meta: "lecture 12" },
      { kind: "ARTICLE", title: "Slow Media Manifesto", meta: "read · saved" },
      { kind: "CONCEPT", title: "Anti-fragility", meta: "Taleb · 2 projects" },
    ],
  },
  {
    id: "experience",
    index: "02",
    name: "Experience",
    purpose: "Lived reality and emotional memory.",
    tagline: "Life experiences and consumption — what you watched, played, walked through, felt.",
    toneLabel: "WARM MAGENTA-PURPLE · EMOTIONAL",
    hue: "oklch(0.7 0.2 330)",
    hue2: "oklch(0.6 0.22 350)",
    domains: [
      { id: "games", name: "Games", blurb: "Worlds inhabited.", count: 38, icon: "gamepad" },
      {
        id: "movies",
        name: "Movies",
        blurb: "Films and series watched.",
        count: 211,
        icon: "film",
      },
      { id: "travel", name: "Travel", blurb: "Journeys taken.", count: 14, icon: "plane" },
      {
        id: "events",
        name: "Events",
        blurb: "Shows, concerts, gatherings.",
        count: 27,
        icon: "calendar-days",
      },
      {
        id: "achievements",
        name: "Achievements",
        blurb: "Milestones earned.",
        count: 9,
        icon: "trophy",
      },
      {
        id: "screenshots",
        name: "Screenshots",
        blurb: "Visual fragments.",
        count: 1284,
        icon: "image",
      },
      {
        id: "clips",
        name: "Clips",
        blurb: "Short moments captured.",
        count: 67,
        icon: "clapperboard",
      },
      {
        id: "moments",
        name: "Personal Moments",
        blurb: "Small, marked, kept.",
        count: 152,
        icon: "sparkles",
      },
    ],
    recent: [
      { kind: "GAME", title: "Dark Souls III", meta: "Played · 78h · platinum" },
      { kind: "FILM", title: "Solaris (1972)", meta: "Tarkovsky · watched 3x" },
      { kind: "JOURNEY", title: "Kyoto — November", meta: "11 days · 248 photographs" },
      { kind: "CLIP", title: "Aurora over Tromsø", meta: "recorded · 02:14" },
      { kind: "ALBUM", title: "In Rainbows", meta: "Radiohead · 312 plays" },
      { kind: "ACHIEVEMENT", title: "First Marathon", meta: "Berlin · 04:21:08" },
    ],
  },
  {
    id: "creation",
    index: "03",
    name: "Creation",
    purpose: "Expression. Production. Output.",
    tagline: "What you've made, written, designed, composed.",
    toneLabel: "DEEP VIOLET · GENERATIVE ENERGY",
    hue: "oklch(0.68 0.22 300)",
    hue2: "oklch(0.55 0.24 295)",
    domains: [
      {
        id: "writing",
        name: "Writing",
        blurb: "Drafts and finished prose.",
        count: 73,
        icon: "pen-line",
      },
      {
        id: "essays",
        name: "Essays",
        blurb: "Long-form arguments.",
        count: 19,
        icon: "scroll-text",
      },
      { id: "code", name: "Code", blurb: "Repos and snippets.", count: 42, icon: "code" },
      {
        id: "projects",
        name: "Projects",
        blurb: "Work in motion.",
        count: 6,
        icon: "folder-kanban",
      },
      { id: "ideas", name: "Ideas", blurb: "Seeds, half-formed.", count: 211, icon: "lightbulb" },
      {
        id: "experiments",
        name: "Experiments",
        blurb: "Things tried, things learned.",
        count: 21,
        icon: "flask",
      },
      {
        id: "designs",
        name: "Designs",
        blurb: "Sketches, frames, systems.",
        count: 88,
        icon: "palette",
      },
      { id: "music", name: "Music", blurb: "Compositions and stems.", count: 12, icon: "music" },
    ],
    recent: [
      { kind: "PROJECT", title: "KOS — prototype v0.1", meta: "active · 38 commits" },
      { kind: "ESSAY", title: "On Attention as Currency", meta: "draft · 2,140 words" },
      { kind: "CODE", title: "graph-walker", meta: "Rust · open source" },
      { kind: "DESIGN", title: "Ambient UI explorations", meta: "Figma · 24 frames" },
      { kind: "MUSIC", title: "Untitled — A minor", meta: "sketch · 03:42" },
      { kind: "IDEA", title: "Memory as terrain", meta: "captured 03:11 AM" },
    ],
  },
  {
    id: "memory",
    index: "04",
    name: "Memory",
    purpose: "Continuity of identity over time.",
    tagline: "Personal history — moments, people, the throughline.",
    toneLabel: "DARK INDIGO · NOSTALGIC",
    hue: "oklch(0.55 0.16 270)",
    hue2: "oklch(0.4 0.14 275)",
    domains: [
      {
        id: "timeline",
        name: "Timeline Events",
        blurb: "Life, laid out in seasons.",
        count: 412,
        icon: "clock",
      },
      {
        id: "diary",
        name: "Diary Entries",
        blurb: "Days as written.",
        count: 1864,
        icon: "notebook-pen",
      },
      { id: "people", name: "People", blurb: "Who walked with you.", count: 184, icon: "users" },
      { id: "family", name: "Family", blurb: "The closest orbit.", count: 22, icon: "heart" },
      {
        id: "moments",
        name: "Important Moments",
        blurb: "Pinned forever.",
        count: 64,
        icon: "star",
      },
    ],
    recent: [
      { kind: "EVENT", title: "Moved to Lisbon", meta: "Nov 14, 2024" },
      { kind: "PERSON", title: "Letters with M.", meta: "12 entries · 6 years" },
      { kind: "MOMENT", title: "Grandfather's last summer", meta: "marked · 1998" },
      { kind: "DIARY", title: "On a quiet Sunday", meta: "1,204 words · today" },
      { kind: "FAMILY", title: "Sister's wedding", meta: "Porto · June" },
      { kind: "EVENT", title: "First job · Day 1", meta: "Sep 02, 2014" },
    ],
  },
  {
    id: "discovery",
    index: "05",
    name: "Discovery",
    purpose: "A knowledge connection engine.",
    tagline: "Patterns the system has noticed across your life.",
    toneLabel: "LUMINOUS PURPLE · CONNECTION",
    hue: "oklch(0.78 0.18 310)",
    hue2: "oklch(0.7 0.2 290)",
    domains: [
      {
        id: "connections",
        name: "Connections",
        blurb: "Entities the system has bridged.",
        count: 312,
        icon: "link",
      },
      {
        id: "patterns",
        name: "Patterns",
        blurb: "Recurring shapes in your thought.",
        count: 47,
        icon: "network",
      },
      {
        id: "insights",
        name: "Cross-Domain Insights",
        blurb: "Ideas that crossed worlds.",
        count: 28,
        icon: "telescope",
      },
      {
        id: "suggestions",
        name: "Relationship Suggestions",
        blurb: "Bridges waiting to be made.",
        count: 14,
        icon: "git-branch",
      },
    ],
    recent: [
      {
        kind: "CONNECTION",
        title: "Outer Wilds ↔ The Order of Time",
        meta: "shared concept: loops",
      },
      { kind: "PATTERN", title: "“Slow promise” recurs in 4 essays", meta: "writing · 2024–2026" },
      { kind: "INSIGHT", title: "Stigmergy ↔ Pattern Language", meta: "ants → architecture" },
      { kind: "SUGGESTION", title: "Bridge: Rovelli ↔ Brand", meta: "time as material" },
      { kind: "PATTERN", title: "Three reads share one idea", meta: "time, granularity" },
      { kind: "CONNECTION", title: "Kyoto trip ↔ essay on attention", meta: "stillness" },
    ],
  },
  {
    id: "legacy",
    index: "06",
    name: "Legacy",
    purpose: "What remains and is passed forward.",
    tagline: "Curated wisdom — principles, teachings, things worth keeping.",
    toneLabel: "DEEP STABLE PURPLE-BLACK · ENDURING",
    hue: "oklch(0.5 0.12 295)",
    hue2: "oklch(0.35 0.1 290)",
    domains: [
      {
        id: "principles",
        name: "Principles",
        blurb: "Rules you live by.",
        count: 24,
        icon: "compass",
      },
      {
        id: "teachings",
        name: "Teachings",
        blurb: "Lessons offered to others.",
        count: 18,
        icon: "book-marked",
      },
      {
        id: "lessons",
        name: "Life Lessons",
        blurb: "Hard-won understandings.",
        count: 41,
        icon: "feather",
      },
      {
        id: "shared",
        name: "Shared Knowledge",
        blurb: "Distilled and public.",
        count: 9,
        icon: "network",
      },
      {
        id: "wisdom",
        name: "Curated Wisdom",
        blurb: "What you'd hand to a stranger.",
        count: 33,
        icon: "star",
      },
    ],
    recent: [
      { kind: "PRINCIPLE", title: "Build for the long now.", meta: "since 2019" },
      { kind: "LESSON", title: "Patience compounds.", meta: "noted · re-noted" },
      { kind: "TEACHING", title: "On reading slowly", meta: "shared · 412 reads" },
      { kind: "WISDOM", title: "Solitude is a workshop.", meta: "kept" },
      { kind: "SHARED", title: "A letter to my future self", meta: "open · 2034" },
      { kind: "PRINCIPLE", title: "Make less, deeper.", meta: "central" },
    ],
  },
];
